name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site directory
        run: |
          rm -rf public
          mkdir public
          # copy everything except Git internals into public
          # (adapt if you have build steps)
          shopt -s dotglob || true
          cp -R . public
          # remove the .github directory from published site
          rm -rf public/.github

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
